# GitHub Action


name: Generate Snake


on:
  schedule:
      # every 12 hours
    - cron: "0 */12 * * *"

# This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    # Generates the snake
      - name: generate snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs:
            dist/solvedac-snake.svg?color_snake=orange&color_dots=#dedfe1,#7cf7ff,#94cafe,#c38ded,#fd7eab

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
